### ISSUE TITLE
How to write all the data in one .csv file ?

### ISSUE THREAD

**Issue by sagariosdev** [SensingKit/CrowdSense-iOS#1]
I want to make a one .csv file with all the enable sensors data.

Right now all .csv file are separated by sensor type but I want all columns should be merge in single file.

How should I do this?
Thanks.

**Comment by minoskt** [comment]
Hello

This is not supported as each sensor data have different structure and the columns won't match. A solution could be to use a JSON structure instead, but this will highly increase the size of the file.

May I ask you what is the reason you need one file instead of multiple?

Thank you
Minos
